[project]
name = 'Medical-Consent-Contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Medical-Consent-Contract]
path = 'contracts/Medical-Consent-Contract.clar'
clarity_version = 3
epoch = 3.1

[contracts.Consent-Template-Manager]
path = 'contracts/Consent-Template-Manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.Consent-Audit-Notifications]
path = 'contracts/Consent-Audit-Notifications.clar'
clarity_version = 3
epoch = 3.1

[contracts.Consent-Delegation-Manager]
path = 'contracts/Consent-Delegation-Manager.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
